//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public int id { get; set; }
        public int id_ThanhVien_DangBaiViet { get; set; }
        public int id_ChuDe { get; set; }
        public Nullable<int> id_AnhNen { get; set; }
        public string TenBaiViet { get; set; }
        public string MoTa { get; set; }
        public string NoiDungBaiViet { get; set; }
        public string Nguon { get; set; }
        public Nullable<int> SoLuotXem { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual ChuDe ChuDe { get; set; }
        public virtual TapTin TapTin { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
