//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongThaoLuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongThaoLuan()
        {
            this.ChatUserDetailsRooms = new HashSet<ChatUserDetailsRoom>();
            this.NoiDungTinNhanPhongThaoLuans = new HashSet<NoiDungTinNhanPhongThaoLuan>();
        }
    
        public int id { get; set; }
        public int id_LoaiPhongThaoLuan { get; set; }
        public string TenPhong { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public bool TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatUserDetailsRoom> ChatUserDetailsRooms { get; set; }
        public virtual LoaiPhongThaoLuan LoaiPhongThaoLuan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoiDungTinNhanPhongThaoLuan> NoiDungTinNhanPhongThaoLuans { get; set; }
    }
}
