//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThangDoiChieu
    {
        public int id { get; set; }
        public int id_LoaiXetNghiem { get; set; }
        public Nullable<double> CanTren { get; set; }
        public Nullable<double> CanDuoi { get; set; }
        public string DonVi { get; set; }
        public string LoiKhuyenVuotQuaCanTren { get; set; }
        public string ChuanDoanBenhKhiVuotQuaCanTren { get; set; }
        public string LoiKhuyenVuotQuaCanDuoi { get; set; }
        public string ChuanDoanBenhKhiVuotQuaCanDuoi { get; set; }
        public Nullable<System.DateTime> NgayApDung { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual LoaiXetNghiem LoaiXetNghiem { get; set; }
    }
}
