//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DuAnYTeEntities : DbContext
    {
        public DuAnYTeEntities()
            : base("name=DuAnYTeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HuyetHoc> HuyetHocs { get; set; }
        public virtual DbSet<HuyetHoc_TapTin> HuyetHoc_TapTin { get; set; }
        public virtual DbSet<NuocTieu> NuocTieux { get; set; }
        public virtual DbSet<NuocTieu_TapTin> NuocTieu_TapTin { get; set; }
        public virtual DbSet<SieuAm> SieuAms { get; set; }
        public virtual DbSet<SieuAm_TapTin> SieuAm_TapTin { get; set; }
        public virtual DbSet<SinhHoaMau> SinhHoaMaus { get; set; }
        public virtual DbSet<SinhHoaMau_TapTin> SinhHoaMau_TapTin { get; set; }
        public virtual DbSet<TapTin> TapTins { get; set; }
        public virtual DbSet<ThanhVien> ThanhViens { get; set; }
    }
}
