//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhHoaMau_TapTin
    {
        public int id_SinhHoaMau { get; set; }
        public int id_TapTin { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual SinhHoaMau SinhHoaMau { get; set; }
        public virtual TapTin TapTin { get; set; }
    }
}
