//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TapTin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TapTin()
        {
            this.HuyetHoc_TapTin = new HashSet<HuyetHoc_TapTin>();
            this.NuocTieu_TapTin = new HashSet<NuocTieu_TapTin>();
            this.SieuAm_TapTin = new HashSet<SieuAm_TapTin>();
            this.SinhHoaMau_TapTin = new HashSet<SinhHoaMau_TapTin>();
        }
    
        public int id { get; set; }
        public string TenTapTin { get; set; }
        public string LoaiTapTin { get; set; }
        public string DuongDan { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HuyetHoc_TapTin> HuyetHoc_TapTin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NuocTieu_TapTin> NuocTieu_TapTin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SieuAm_TapTin> SieuAm_TapTin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinhHoaMau_TapTin> SinhHoaMau_TapTin { get; set; }
    }
}
